version: '3.2'
services:
  wifipumpkin3:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/wifipumpkin3:v2025.04.16-action
    privileged: true
    network_mode: "host"
    container_name: wifi
    hostname: wifi
    volumes:
      - ./scripts:/root/.config/wifipumpkin3/scripts
      - ./logs:/root/.config/wifipumpkin3/logs
      - ./config:/root/.config/wifipumpkin3/config
      - ./:/usr/src/app
      - ./start.sh:./start.sh
